# Site settings
title: Capital Tattoo - Столичная Студия Татуировки
description: Capital Tattoo, столичная студия татуировки
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://akoppela.github.io/capital-tattoo" # the base hostname & protocol for your site

# Build settings
markdown: kramdown