# Site settings
title: Capital Tattoo - Столичная Студия Татуировки
description: Capital Tattoo, столичная студия татуировки
baseurl: "/capital-tattoo" # the subpath of your site, e.g. /blog/
url: "http://akoppela.github.io" # the base hostname & protocol for your site
emptyArray: []
emptyObject: {}

# Build settings
markdown: kramdown