# Site settings
title: Capital Tattoo - Столичная Студия Татуировки
description: Capital Tattoo, столичная студия татуировки
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://www.capitaltattoo.ru/" # the base hostname & protocol for your site
emptyArray: []

# Build settings
markdown: kramdown

gems:
  - jekyll-redirect-from