- title: Художественная татуировка
  photo: tattoo.jpg
  text:
    - ' Татуировка – это рисунок на теле и процесс нанесения рисунка на кожу, путем ее травмирования, с внесением в подкожную клетчатку определенного пигмента. Это «сухое» и официальное определение, между тем, не раскрывает  истинной сути вещей.'
    - 'Во все времена татуировка служила индивидуальным отличием каких - либо качеств в человеке или определенной принадлежности человека к чему - либо.  Уровень современных мастеров - профессионалов позволяет сказать, что татуировка - это целое искусство. Будь то следование модным тенденциям, или память о чем-то очень важном и дорогом в вашей жизни, татуировка, в той или иной степени - это художественное отражение вашего внутреннего мира. Татуировка - это ваша индивидуальность. И в этом вопросе не стоит пренебрегать в выборе мастера.'

- title: Пирсинг любых частей тела
  photo: piercing.jpg

- title: Перманентный макияж
  photo: makeup.jpg

- title: Лазерное удаление татуировки
  photo: lazer.jpg