- id: tattoo
  title: Художественная татуировка
  short_title: Татуировка
  photo: tattoo.jpg
  text:
    - ' Татуировка – это рисунок на теле и процесс нанесения рисунка на кожу, путем ее травмирования, с внесением в подкожную клетчатку определенного пигмента. Это «сухое» и официальное определение, между тем, не раскрывает  истинной сути вещей.'
    - 'Во все времена татуировка служила индивидуальным отличием каких - либо качеств в человеке или определенной принадлежности человека к чему - либо.  Уровень современных мастеров - профессионалов позволяет сказать, что татуировка - это целое искусство. Будь то следование модным тенденциям, или память о чем-то очень важном и дорогом в вашей жизни, татуировка, в той или иной степени - это художественное отражение вашего внутреннего мира. Татуировка - это ваша индивидуальность. И в этом вопросе не стоит пренебрегать в выборе мастера.'
  
  groups:
    - title: Цены
      prices:
        - title: Создание эскиза
          price: Бесплатно
        - title: Стартовая цена на татуировку
          price: 1000 руб
        - title: Стоимость 1 часа работы мастера студии
          price: 3000 руб
        - title: Стоимость трёх-часового сеанса
          price: 6000 руб
        - title: Стоимость пяти-часового сеанса
          price: 9000 руб
  
  subtext: '* Стоимость татуировки, требующей одного сеанса и более, зависит от сложности и размера рисунка.<br />
            Стоимость сеанса работы у ведущего мастера студии обсуждается на консультации.'
  
  why_choose_us: 'Опытные мастера сделают татуировку любой сложности. Экологически чистые и долговечные красящие вещества. Надежное оборудование и одноразовые контактные материалы. Эскиз татуировки - бесплатно!'

- id: piercing
  title: Пирсинг любых частей тела
  short_title: Пирсинг
  photo: piercing.jpg
  text:
    - 'Пирсинг – это эффективный и очень популярный способ модификации и украшения собственного тела, суть которого в создании прокола на отдельном его участке и введение в это место украшения. Вопреки распространенному мнению, пирсинг далеко не всегда удел продвинутой молодежи. Даже прокалывание мочки уха является разновидностью пирсинга. Хотя чаще всего этим словом обозначают более «экстремальные» проколы: носа, пупка, языка, возле уголка рта и др.'
    - 'Велико и разнообразие используемых при этом украшений: от маленьких до больших, от простых до созданных из драгоценных металлов и камней. Мастера Capital tattoo проконсультируют и помогут в выборе украшения для пирсинга с учетом места прокола. У нас вы можете приобрести разнообразные спирали, кольца, лабреты для языка, губ, пупка, уха или брови. Также возможно прокалывание и с использованием украшения клиента, при условии, если оно подходит для первичного прокола.'
  
  groups:
    - title: Пирсинг лица
      prices:
        - title: Губа (смайл)
          price: 1000 руб
        - title: Губа
          price: 1000 руб
        - title: Губа (симметрия)
          price: 1500 руб
        - title: Нос (септум)
          price: 1500 руб
        - title: Нос (крыло носа)
          price: 1000 руб
        - title: Нос (перегородка)
          price: 1000 руб
        - title: Прокол щек (два прокола)
          price: 1500 руб
        - title: Щека (один прокол)
          price: 1000 руб
        - title: Монро
          price: 1000 руб
        - title: Язык
          price: 1000 руб
        - title: Язык (симметрия)
          price: 1500 руб
        - title: Бровь
          price: 1000 руб
    
    - title: Пирсинг ушей
      prices:
        - title: Козелок
          price: 1000 руб
        - title: Индастриал
          price: 1500 руб
        - title: Хрящик уха
          price: 800 руб
        - title: Мочка уха (пистолет)
          price: 500 руб
        - title: Мочка уха (игла)
          price: 600 руб
        - title: Ухо (трагус)
          price: 1000 руб
        - title: Растяжка ушей
          price: 250 руб/1 мм
    
    - title: Пирсинг тела
      prices:
        - title: Плоскостной пирсинг
          price: от 1000 руб
        - title: Интимный пирсинг
          price: от 2000 руб
        - title: Соски (один прокол)
          price: 1000 руб
        - title: Пупок
          price: 1000 руб
  
  why_choose_us: 'Стерильные и безопасные условия. Многолетний опыт работы. Легкая рука мастеров. Украшение пирсинга - бесплатно!'

- id: makeup
  title: Перманентный макияж
  short_title: Татуаж
  photo: makeup.jpg
  text:
    - 'Татуаж или перманентный макияж представляет собой одну из наиболее популярных и востребованных процедур в современной индустрии красоты. Это отличный способ подчеркнуть внешность и сохранить при этом свою природную естественность. Это возможность полностью отказаться от использования декоративной косметики  и всегда выглядеть ухоженной, в не зависимости от места и времени. На сегодняшний день, существуют различные техники перманентного татуажа.'
    - '<i>Татуаж губ (контур, 3D)</i>
      <i>Татуаж бровей (шатирование, волоски)</i>
      <i>Tатуаж глаз (век)</i>'
    - 'При создании индивидуального образа техники также могут комбинироваться. В отличие от традиционной татуировки, остающейся на всю жизнь, татуаж выполняется специальными красителями, которые со временем теряют первоначальную насыщенность.  Эти краски более чувствительны к воздействию ультрафиолета. Поэтому быстрее светлеет татуаж у людей, злоупотребляющих загаром. Осветление перманентного макияжа с годами зависит от индивидуальных особенностей кожи человека, правильного ухода, который так же требует индивидуального подхода. Важно помнить и следовать всем рекомендациям мастера.'
  
  groups:
    - title: Татуаж бровей
      prices:
        - title: Татуаж межресничного пространства
          price: 4000 руб
        - title: Татуаж бровей (волосковая техника)
          price: 5000 руб
        - title: Татуаж бровей (эффект карандаша)
          price: 5000 руб
        - title: Татуаж бровей (техника растушевки)
          price: 5000 руб
    
    - title: Татуаж глаз
      prices:
        - title: Стрелки на глазах
          price: 5000 руб
    
    - title: Татуаж губ
      prices:
        - title: Контур с растушевкой
          price: 6000 руб
        - title: Контур с покрасом на 1/2 поверхности губ
          price: 7000 руб
        - title: Полный прокрас поверхн
          price: 7000 руб
        - title: Техника акварель
          price: 8000 руб
        - title: Эффект 3D
          price: 8000 руб
  
  why_choose_us: 'Высококачественное оборудование и безопасные условия. Опытные сертифицированные специалисты. Долговечные краски на растительной основе. Консультация - бесплатно!'

- id: lazer
  title: Лазерное удаление татуировки
  short_title: Удаление тату
  photo: lazer.jpg
  text:
    - 'Лазерное удаление татуировок – самый передовой и безопасный метод избавления от некачественного или надоевшего рисунка. Нередко к нам обращаются те, кто хотят исправить неудачный опыт. В этом случае наши мастера помогут сделать, так называемый COVER UP, перекрывающий старые татуировки, либо предложить услугу лазерного удаления тату. В первом случае, вы получаете что-то новое, во втором - навсегда забываете о старом (без шрамов и эффекта выгоревшей кожи).'
    - 'Лазерное удаление подразумевает комплексный подход: вначале, специалист проведет полный и всесторонний анализ цветовых характеристик татуировки и места ее нахождения. Только после этого, грамотно определит механизм удаления. Полное удаление татуировки без шрамов и рубцов - процесс, занимающий не один сеанс - это поэтапная работа. Успех процедуры зависит от правильного ухода,а также реабилитационного периода между сеансами.'
  
  groups:
    - title: От 1000 руб/кв.см. Полное удаление тату. Без шрамов.
  
  why_choose_us: 'Опытные мастера удалят или исправят татуировку любой сложности. Мы используем лазер, не оставляющий шрамов и рубцов. Консультация мастера - бесплатно!'
